version: '3'

services:
  web:
    build: .
    command: >
      bash -c "
            sleep 40 &&
            python manage.py migrations --noinput &&
            python manage.py runserver 0.0.0.0:8000 --noreload"
    
    ports:
      - '8000:8000'
    depends_on:
      - db
  db:
    image: mysql:5.7
    healthcheck:
      test: ["CMD-SHELL", 'mysql --database=$$MYSQL_DATABASE --password=$$MYSQL_ROOT_PASSWORD --execute="SELECT count(table_name) > 0 FROM information_schema.tables;" --skip-column-names -B']
      interval: 30s
      timeout: 10s
      retries: 4
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'db_django'
      MYSQL_ROOT_PASSWORD: 'password'
    restart: always
    