version: "3.7"
   
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: >
      sh -c "sleep 20 &&
              python manage.py migrate --noinput &&
              python manage.py runserver 0.0.0.0:8000 --noreload"
    
    ports:
      - "8000:8000"
    depends_on:
      - db