version: "3.7"
   
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  web:
    build: .
    command: >
      sh -c " python manage.py makemigrations datapage --no-input &&
              python manage.py migrate --no-input &&
              python manage.py initadmin &&
              python manage.py loaddata db.json  &&
              python manage.py runserver 0.0.0.0:8000 --noreload"
    
    ports:
      - "8000:8000"
    links:
      - db
    depends_on:
      db:
        condition: service_healthy